version: '3.8'

services:
  frontend:
    image: frontend/testdevtools:1.0.0
    build: ./front-end
    ports:
      - "8080:80"
    
  backend:
    image: backend/testdevtools:1.0.0
    build: ./back-test/app
    ports:
      - "3001:3000"
    