pipeline {
    agent any
stages {
  
   stage('Pull code') {
       steps {
           checkout scm
       }
    }
    stage('Download dependency') {
       steps {
           dir('back-test/app') {
              echo "jimback"
           }
       }
   }
  
  }
}
